### ISSUE TITLE
机器人获取不到所在目录

### ISSUE THREAD

**Issue by fishfuture** [w4123/CQXQ#1]
如题

**Comment by w4123** [comment]
getAppDirectory还是什么

**Comment by fishfuture** [comment]
就是单纯取运行目录

**Comment by w4123** [comment]
我不知道取运行目录是什么，你是指的CQ_getAppDirectory还是比如GetModuleFilePath

**Comment by fishfuture** [comment]
GetModuleFilePath

**Comment by fishfuture** [comment]
还有CQ_getGroupMemberList也没实现

**Comment by w4123** [comment]
没实现的我当然知道，GetModuleFilePath和CQXQ也没关系啊

**Comment by fishfuture** [comment]
翻了一眼是GetCurrentDirectoryW

**Comment by w4123** [comment]
那也跟CQXQ没关系啊

**Comment by w4123** [comment]
CQ_getGroupMemberList已经实现
