### ISSUE TITLE
bug反馈以及一些提问

### ISSUE THREAD

**Issue by YumemiShitori** [w4123/CQXQ#12]
1. v1.04版本会显示CQXQ初始化API致命错误
2. v1.03版本可以运行，但是在框架日志中会显示，写出CQP.dll失败！无法创建文件输出
3. 请问log插件之后会支持吗？
4. v1.03会出现获取群成员列表失败

**Comment by w4123** [comment]
1. 更新先驱版本
2. 旧版本bug 已修复
3. 不知道你指的是什么
4. 腾讯API限制 正常不会有什么影响

**Comment by ray110wyz** [comment]
代人回复，其他已解决
3是指Dice-Developer-Team/TrpgLogger这个插件，请问以后会不会出支持cqxq的版本
麻烦啦

**Comment by w4123** [comment]
已经集成在Dice里面了，现在就可以用
