### ISSUE TITLE
关于获取网络图片链接

### ISSUE THREAD

**Issue by laomms** [w4123/CQXQ#13]
发送网络图片以 .mnimg 结尾，该文件不落地，例：[CQ:image,file={247E6A8B-ED3A-1B98-15E8-07E2277C787A}.jpg.mnimg]

如何提取该图片链接或者保存该文件用于识别 ?

**Comment by w4123** [comment]
我不知道你是从哪里看到的“发送网络图片以 .mnimg 结尾，该文件不落地，例：[CQ:image,file={247E6A8B-ED3A-1B98-15E8-07E2277C787A}.jpg.mnimg]”这句话，这并不是CQXQ的逻辑

**Comment by laomms** [comment]
我的以上是图片以[pic={0D867203-11BE-B1D1-8529-448780B619F7}.jpg] 的格式存在，没有存储到本地，是不是用CQP.CQ_getImage这个地址就可以获取图片链接?

**Comment by w4123** [comment]
还没写，正在写

**Comment by w4123** [comment]
因为XQ的API获取图片下载链接除了要求类似于{0D867203-11BE-B1D1-8529-448780B619F7}.jpg这个东西以外，还需要这个图片所在的群号，所以我打算改一下传给CQ插件的CQ码的格式……比如改成[CQ:image,file={0D867203-11BE-B1D1-8529-448780B619F7}.jpg.群号]之类的……不然的话我就没法获取

**Comment by laomms** [comment]
消息传入本身就带群号吧。我看到mirai是用CQApi.ReceiveImage("{247E6A8B-ED3A-1B98-15E8-07E2277C787A}.jpg.mnimg")的方式获取本地下载图片路径。

**Comment by w4123** [comment]
不同框架肯定不一样啊

**Comment by laomms** [comment]
1.0.6赞一个
