### ISSUE TITLE
无法正常发送某些图床的图片

### ISSUE THREAD

**Issue by LambdaYH** [w4123/CQXQ#16]
![image](https://user-images.githubusercontent.com/13503375/90316774-196dda80-df57-11ea-8d06-6380b9ff94de.png)
如图，采用`CQXQ1.0.5`以及`cqhttp`插件，发送`sm.ms`图床图片后会发出CQ码？而不是图片
![image](https://user-images.githubusercontent.com/13503375/90316795-39050300-df57-11ea-89c7-3cb9698c992f.png)
疑似图床反爬导致

**Comment by w4123** [comment]
很明显这是因为我没做cache=0这一项，删掉就好了

**Comment by w4123** [comment]
现在cache=0可以正常被忽略了

**Comment by LambdaYH** [comment]
![image](https://user-images.githubusercontent.com/13503375/90532768-351cef00-e1aa-11ea-91dd-7b874a0eb32b.png)
