### ISSUE TITLE
dice2.4.1beta2版+CQXQv1.05版 bug反饋

### ISSUE THREAD

**Issue by YumemiShitori** [w4123/CQXQ#17]
dice2.4.1beta2版+CQXQv1.05版运行条件下：
1.投掷.help以及.coc 6等应答回复字数较多的指令时，骰子无回复，日志显示“似乎被屏蔽信息或丢包状态”这样的内容
2.骰子对.dismiss指令无响应，会显示退群语，但骰子QQ不会退群
3.拉骰子入群时，日志中显示两种类型的错误，（1）“未解析的0057事件”；（2）无效的seq代码
4.骰子入群后需要一段时间才会跳入群语

**Comment by w4123** [comment]
1. 你自己的问题
2. 你自己的问题
3. 先驱已知问题
4. 先驱已知问题
