### ISSUE TITLE
[CQ:pic]不支持base64编码后的图片导致XQ连接断开

### ISSUE THREAD

**Issue by CSGA-KPX** [w4123/CQXQ#18]
如果发送用base64编码图片``base64:///......``，CQXQ会加上路径名变成``[pic=Z:\home\user\coolq\data\image\base64:///...``，之后XQ在处理的时候会提示“Udp连接异常断开A...”然后重连。

**Comment by w4123** [comment]
找时间做，找时间做……

**Comment by w4123** [comment]
已支持
