### ISSUE TITLE
如果收到好友带图片消息直接转发出去，会多带一个参数，导致图片显示不出来

### ISSUE THREAD

**Issue by moumouren** [w4123/CQXQ#19]
![QQ截图20200818071717](https://user-images.githubusercontent.com/38750595/90453317-e0826100-e122-11ea-904b-cbf5504d3fca.png)
上面 橙色的是好友发来的，直接转发到群里会显示不出图片。下面红色圈出来的是正常的，对比能看到图片多了一个好友私聊的参数

**Comment by w4123** [comment]
这个就应该这样，下个版本会做转换

**Comment by w4123** [comment]
已支持

**Comment by moumouren** [comment]
牛逼
