### ISSUE TITLE
关于Linux系统支持

### ISSUE THREAD

**Issue by ray110wyz** [w4123/CQXQ#2]
您好，請問現在CQXQ有支援linux系統嗎？會有像使用coolq時的docker image嗎？還是說必須使用wine去運行？未來有打算開發linux的版本嗎？
感谢——

**Comment by w4123** [comment]
暂时没有但是有计划支持基于wine的docker镜像，直接支持linux不太现实因为XQ本身就只是Windows上的

**Comment by ray110wyz** [comment]
谢谢！
