### ISSUE TITLE
当从聊天窗口获取图片并请求将图片上传时 参数有误

### ISSUE THREAD

**Issue by a563696823** [w4123/CQXQ#20]
![image](https://user-images.githubusercontent.com/63532063/90533483-2be05200-e1ab-11ea-85ce-5ea2d2296b69.png)
![image](https://user-images.githubusercontent.com/63532063/90533544-43b7d600-e1ab-11ea-9b6d-ef587919ec92.png)

**Comment by a563696823** [comment]
使用1.0.6的‘CQXQ’

**Comment by w4123** [comment]
具体？

**Comment by a563696823** [comment]
在0805上不会再提示参数有误，但获取不了图片，看了一下应该是由于聊天接收的图片在本地没有缓存而导致的。

**Comment by w4123** [comment]
我完全不理解你的问题，因为我完全不知道你的这个/image upload命令是用来做什么的
并且暂时来说，没有人在上传图片（指在QQ发送）的时候遇到问题
并且**CQXQ不会缓存图片**，设计就是这样的，并且**这和获取不了图片没有关系**
请更加详细的描述你问题，至少让我明白你究竟在做什么

**Comment by a563696823** [comment]
刚刚表述有误，获取不了图片不是先驱也不是CQXQ获取不了。
这个命令主要是将命令之后后接的图片上传到图床。由于接收的图片没有缓存，因此在尝试上传时候，CQHTTP那边的服务端会获取不到图片的信息。[image upload](https://github.com/Bluefissure/OtterBot/blob/ff53793125a0663ac760fb83e9bc5011ac0a544e/ffxivbot/handlers/QQCommand_image.py#L59)

**Comment by w4123** [comment]
你需要先通过CQ_getImage这个方法获取到图片的链接，然后从链接下载图片，最后把图片上传
我不觉得这个和缓存之类的有什么关系

**Comment by LambdaYH** [comment]
好，通过手打CQ码上传测试成功了，应该和CQXQ这边没关系了，但不知道为什么CQHTTPmirai那边可以正常用。
麻烦你了!

**Comment by a563696823** [comment]
通过手打CQ码上传成功了，不是CQXQ的关系，但不知道为什么CQHTTPmirai那边可以正常用。
麻烦你了!
