### ISSUE TITLE
启用后报错

### ISSUE THREAD

**Issue by mexiaow** [w4123/CQXQ#28]
日志显示
![Snipaste_2020-08-29_13-36-31](https://user-images.githubusercontent.com/57959986/91629579-c5ee9880-e9fc-11ea-8e56-1eaf2c8485b8.png)

问题签名:
  问题事件名称:	BEX
  应用程序名:	先驱.exe
  应用程序版本:	1.0.0.0
  应用程序时间戳:	5f3ab73d
  故障模块名称:	CQXQ.XQ.dll
  故障模块版本:	0.0.0.0
  故障模块时间戳:	5f400286
  异常偏移:	0007f84c
  异常代码:	c0000409
  异常数据:	00000007
  OS 版本:	6.3.9600.2.0.0.400.8
  区域设置 ID:	2052
  其他信息 1:	cd7e
  其他信息 2:	cd7e0dd5570e664260b1bc1af3b8b9a0
  其他信息 3:	d144
  其他信息 4:	d14410665c227583e806f5fb273daec2

**Comment by w4123** [comment]
自己放个zlib1.dll到根目录啊
