### ISSUE TITLE
在先驱插件界面右键设置插件，CQXQ未响应

### ISSUE THREAD

**Issue by 1135890950** [w4123/CQXQ#29]
![无标题2](https://user-images.githubusercontent.com/40441060/91647956-e453a300-ea93-11ea-9f83-0cd11412240c.png)
如图所示
系统是Server 2012 R2
换回1.0.7的CQXQ就没问题
对了，在更新插件前重启了下先驱，然后先驱的自动更新程序更新了node.dll，不知道和这个有没有关系

**Comment by w4123** [comment]
已修复
