### ISSUE TITLE
登录QQ后报错

### ISSUE THREAD

**Issue by wpyok500** [w4123/CQXQ#3]
21|12:23:19|先驱|异常|警告:程序发生错误
错误代码:-532462766(0xE0434352)
发生位置:0x75985608
相对地址:[KERNELBASE.dll].0x00015608
分析位置:0x07472A1B
错误参数1:-2146233052(0x80131524)
错误参数2:0(0x00000000)
错误参数3:0(0x00000000)
错误参数4:0(0x00000000)
错误参数5:1704722432(0x659C0000)
CallStack:
 [KERNELBASE.dll].RaiseException+0x48
  0x65B770F1
   0x65B22D82
    0x65D69CFD
     [clr.dll]+0xF0EC=659CF0EC
      0x07472A1B
       0x074700BC
        0x09CFEA57
         0x09CFE49A
          0x09CFDF4A
           0x09CFDD44
            [CQXQ.XQ.dll].XQ_Event+0x04ED
             [先驱.exe]+0x001C5973=005C5973
              [005C59FD]FUNCTION:plugin.send
               [00529731]FUNCTION:push插件

异常线程ID:5916
框架版本号：2020080301

**Comment by w4123** [comment]
装了哪些CQ插件？一个个移除出去看看是哪个导致的错误？
