### ISSUE TITLE
关于cqhttp的加载

### ISSUE THREAD

**Issue by Madokadaisuki** [w4123/CQXQ#33]
我通过cqhttp作者的github的release页面：https://github.com/richardchien/coolq-http-api/releases
下载了到了一个json和dll文件，但是当我按照readme页面的说明将它们放入cqplugis文件后，加载先驱框架却提示loadlibrary错误：126，我进行网上搜索后无法确定应该排查哪里的问题，还望指教

**Comment by w4123** [comment]
你依赖没下全，libiconv之类的

**Comment by 10935336** [comment]
您好，我遇到了同样的问题，我获取了cqhttp需要的libiconv.dll和sqlite3.dll，但不知道该放在哪里，可以请教一下吗？
