### ISSUE TITLE
CQ_getStrangerInfo接口信息性别和年龄注释掉了，可以打开吗？

### ISSUE THREAD

**Issue by azraellamber** [w4123/CQXQ#36]
想问下能不能打开 CQ_getStrangerInfo 接口里用到的XQ接口
XQAPI::GetGender
和
XQAPI::GetAge

我看代码里有的，但是注释掉了，不知道为啥，是XQ的实现有问题么？
之前的代码刚好用到了这两个信息判断了下对对方的称呼。

**Comment by w4123** [comment]
你可以自己打开

**Comment by azraellamber** [comment]
明白了，感谢，这次更新了cmake之后可以本地编译了，这两接口我开了看了，应该xq的api返回就没对。
