### ISSUE TITLE
无法加载  cqcppsdk 编写的插件？

### ISSUE THREAD

**Issue by HeartyYF** [w4123/CQXQ#39]
https://github.com/kyubotics/cqcppsdk 编写的插件，尝试加载后报出错误
![image](https://user-images.githubusercontent.com/17660052/104930617-58113080-59e0-11eb-8740-d850492c7bae.png)

**Comment by w4123** [comment]
点一下详细信息？

**Comment by HeartyYF** [comment]
![image](https://user-images.githubusercontent.com/17660052/104931918-079ad280-59e2-11eb-9450-dd895f2b5c7e.png)
嗯……似乎是调用了什么奇怪的coolq函数？

**Comment by w4123** [comment]
根据代码分析，你的应用缺少libiconv.dll……，请自行下载或编译然后放到根目录

**Comment by HeartyYF** [comment]
已解决，感激不尽。

**Comment by HeartyYF** [comment]
另外发现一个小问题，就是在路径有中文时（比如解压后文件名中自带的先驱之类的）ofstream不能正常写入文件，不清楚是XQ本来如此还是怎么回事。

**Comment by w4123** [comment]
你是指你自己代码中的ofstream? 估计是路径编码问题。试一下设置locale或者转换编码。
