### ISSUE TITLE
使用dismiss指令无法使骰子退群

### ISSUE THREAD

**Issue by mihonskka** [w4123/CQXQ#4]
[新建文本文档 (7).txt](https://github.com/w4123/CQXQ/files/5050575/7.txt)
这是复制下来的日志
使用了.dismiss指令后无效

**Comment by w4123** [comment]
dismiss无效一般是网络问题，检查一下网络状态
里面的那个警告是个bug，已经修了

**Comment by mihonskka** [comment]
okay
