### ISSUE TITLE
当一个CQXQ机器人发送给另一个CQXQ机器人消息时。。

### ISSUE THREAD

**Issue by Kintakumi** [w4123/CQXQ#5]
不知道原因是什么，但是另一个CQXQ机器人不会处理前一个机器人有换行的消息（消息内有\n换行）

**Comment by w4123** [comment]
只有CQXQ有这个现象吗，比如正常用户发消息带换行会正常响应吗
另外最好发下日志

**Comment by Kintakumi** [comment]
正常用户是会响应的 今早我发一下

**Comment by Kintakumi** [comment]
不，正常用户也不会响应（我使用手机发送的，刚刚试了）

**Comment by w4123** [comment]
那样这个问题就看起来正常多了……我明天看下

**Comment by Kintakumi** [comment]
很奇怪，电脑端QQ换行消息貌似可以处理，手机端发出的就不行，CQXQ发给CQXQ也不行

**Comment by Kintakumi** [comment]
貌似已经解决了，使用了2020年8月的先驱机器人即可
