### ISSUE TITLE
GetGroupMemberInfo报错

### ISSUE THREAD

**Issue by cucibala** [w4123/CQXQ#6]
197846****总共十位的qq号调用GetGroupMemberInfo方法时会  ”报算术运算导致溢出。“

**Comment by w4123** [comment]
我不认为这和CQXQ有关

**Comment by w4123** [comment]
另外我自己就是十位数的QQ并没有遇到这个问题……

**Comment by cucibala** [comment]
奇怪昨天同样一段发言，昨天报错今天测试又没问题了

**Comment by w4123** [comment]
我猜有可能是你装的某个插件之类的导致的……可以自己查一下，这个issue我先关了如果还有问题就再开

**Comment by cucibala** [comment]
![image](https://user-images.githubusercontent.com/48320342/90130302-d1a35380-dd9c-11ea-9934-e70a37107bab.png)
fromGroup.getGourpMemberInfo().NIck
![image](https://user-images.githubusercontent.com/48320342/90130357-ebdd3180-dd9c-11ea-941c-06cf6a9c990c.png)

**Comment by w4123** [comment]
我没有遇到这个问题，这个更有可能是你自己的代码导致的我寻思……

**Comment by cucibala** [comment]
问题是我把我的代码放在mirai-native-console，兼容酷q的插件上面可以正常运行

**Comment by w4123** [comment]
1. 你用的是最新版的CQXQ吗
2. 你调用这个函数的时候控制台有输出“获取群成员列表失败吗”

首先这个错误信息本身很难来自CQXQ，因为CQXQ在任何情况下都不会输出一个中文的错误信息到Nick里面或者怎么样
如果你说是先驱框架输出的也不太可能，因为他也不会在获取群列表的时候返回一个中文的错误信息，发生错误也只会在日志中打印
所以这个错误信息本身基本是你代码中自己写的，那么你是怎么解析GetGroupMemberInfo获得的信息的，是哪部分代码导致了输出这条错误信息的呢

**Comment by cucibala** [comment]
1.我是用的是V1.0.3
2.控制台没有输出“获取群成员列表失败"
3.我用先驱加载插件debug的时候是有获取到data的
![image](https://user-images.githubusercontent.com/48320342/90158248-5738fa80-ddc1-11ea-969d-76f88112a6b2.png)
但是用这个数据去初始化GroupMemberInfo的时候会出错(sdk完成的初始化操作).
同样我用mirai加载插件也能获取到data，但是能够正确的生成GroupMemberInfo.

**Comment by w4123** [comment]
OK感谢反馈，有你的SDK的Github地址或者什么吗我去对比一下

**Comment by cucibala** [comment]
https://github.com/Jie2GG/Native.Framework

**Comment by w4123** [comment]
已修复，请测试

**Comment by cucibala** [comment]
是替换CQXQ的版本吗

**Comment by cucibala** [comment]
> 是替换CQXQ的版本吗

我不会编译，可以发布一下新的release的版本吗

**Comment by w4123** [comment]
已发布
