### ISSUE TITLE
一些酷Q接口的定义错误

### ISSUE THREAD

**Issue by ExerciseBook** [w4123/CQXQ#8]
1.

https://github.com/w4123/CQXQ/blob/master/CQXQ/CQTools.cpp#L153

https://github.com/w4123/CQXQ/search?q=gbk&unscoped_q=gbk

酷Q的定义是 gb18030 而非 gbk 。

gb18030 是 unicode 的一个实现，因此 `CQ:emoji` 理论上感觉可以直接舍弃。

2. 

既然 `CQ:emoji` 还没写，那就来点抄作业。
`CQ:emoji` 存在很多 bug ，个人不是很建议复刻，如果要复刻的话我给一下 cqhttp 的代码片段。
https://github.com/richardchien/coolq-http-api/blob/87b6c3d1b6491fde564aecf5e2d42c458e6cfd91/src/cqsdk/utils/string.cpp#L89
长话短说是
```
1. [CQ:emoji,id={CODEPOINT}]
2. 当 {CODEPOINT} 大于 100000 需要给他减去 100000
```

**Comment by ExerciseBook** [comment]
太难过了，希望能对 repo 主有点帮助。

**Comment by w4123** [comment]
我知道是GB18030 但是因为转换用的是WideCharToMultiByte, 用GB18030会在wine上出问题（因为wine没有实现GB18030所以先用的GBK
等我换成第三方库（libiconv）我再用GB18030
反正一般用GBK也不会出什么大问题……

**Comment by ExerciseBook** [comment]
啊 确实，wine 下没 gb18030 。

**Comment by laomms** [comment]
一些特殊字符经过转发后变成乱码, 比如 ⇇  ⇊ ⇋  ⇒ ⇓ ➾ 之类的.

**Comment by w4123** [comment]
小问题，小问题

**Comment by ExerciseBook** [comment]
小问题，等之后换成 gb18030 可能就会好一点了。先鸽会儿。

**Comment by HeartyYF** [comment]
经测， ⇇ ⇊ ⇋ ⇒ ⇓ ➾ 之类的特殊字符还是会变成 ?? 这样的东西
