### ISSUE TITLE
当我要求机器人发送私聊图片时。。

### ISSUE THREAD

**Issue by Kintakumi** [w4123/CQXQ#9]
当我要求机器人发送私聊图片时，机器人显示
![image](https://user-images.githubusercontent.com/56346548/90111991-ffc76a00-dd81-11ea-9fb8-2cfe485b28f5.png)
然而随后无动静，群内发图是可以的，后来发现私聊的图片格式是
![image](https://user-images.githubusercontent.com/56346548/90112081-1cfc3880-dd82-11ea-9e58-dd942c8a837f.png)
所以好像不能发出图片的样子
以及当出现私聊与群聊互发图片的时候也是无法互发的（但是私聊到群聊可以检测并删除前缀，群聊到私聊就不知道了）

**Comment by Kintakumi** [comment]
![image](https://user-images.githubusercontent.com/56346548/90112316-65b3f180-dd82-11ea-9446-7c19fe5804af.png)
这是群聊发送图片

**Comment by w4123** [comment]
暂时不支持直接通过URL发图，请先下载到本地

**Comment by w4123** [comment]
理论上现在通过[CQ:image,url=xxx]可以发图了
